CREATE TABLE CatProducto(
ID_CATPRODUCTO int,
nombre varchar(10) not null,
descripcion varchar(40) not null,
precio int not null,
stock int not null,
imagen varchar(200) not null,
duracion int not null,
sabor varchar(12) not null,
iva int not null,
estado boolean not null,
FK_ID_SUBTIPOPRODUCTO int not null,
primary key(ID_CATPRODUCTO));

CREATE TABLE SubtipoProducto(
ID_SUBTIPOPRODUCTO int,
nombre varchar(10) not null,
FK_ID_TIPOPRODUCTO int not null,
primary key(ID_SUBTIPOPRODUCTO));

CREATE TABLE TipoProducto(
ID_TIPOPRODUCTO int,
nombre varchar(16),
primary key(ID_TIPOPRODUCTO));

CREATE TABLE Produccion(
ID_PRODUCCION int,
FK_ID_CALENDARIO int,
fechaProduccion date not null,
unidades int not null,
cantidadInicial int not null,
FK_ID_CATPRODUCTO int not null,
primary key(ID_PRODUCCION, FK_ID_CALENDARIO));

CREATE TABLE Venta(
ID_VENTA int,
fecha date not null,
primary key(ID_VENTA));

CREATE TABLE Calendario(
ID_CALENDARIO int,
nombre varchar(30) not null,
hora varchar(5) not null,
detalles varchar(50) not null,
primary key(ID_CALENDARIO));

CREATE TABLE EventoEspecifico(
ID_EVENTOESPECIFICO int,
FK_ID_CALENDARIO int,
fecha date not null,
primary key(ID_EVENTOESPECIFICO, FK_ID_CALENDARIO));

CREATE TABLE MateriaPrima(
ID_MATERIAPRIMA int,
nombre varchar(10) not null,
cantidad int not null,
descripcion varchar(30) not null,
precio int not null,
iva int not null,
duracion int not null,
stock int not null,
FK_ID_CALENDARIO int not null,
primary key(ID_MATERIAPRIMA));

CREATE TABLE MedidaCantidad(
ID_MEDIDACANTIDAD int,
nombre varchar(3) not null,
FK_ID_MATERIAPRIMA int not null,
primary key(ID_MEDIDACANTIDAD));

CREATE TABLE TipoMateriaPrima(
ID_TIPOMATERIAPRIMA int,
nombre varchar(15) not null,
FK_ID_MATERIAPRIMA int not null,
primary key(ID_TIPOMATERIAPRIMA));

CREATE TABLE Proveedor(
ID_PROVEEDOR int,
prNombre varchar(10) not null,
segNombre varchar(10) not null,
prApellido varchar(10) not null,
segApellido varchar(10) not null,
correo varchar(30) not null,
estado boolean not null,
primary key(ID_PROVEEDOR));

CREATE TABLE Insumo(
ID_INSUMO int,
nombre varchar(10) not null,
stock int not null,
descripcion varchar(30) not null,
precio int not null,
cantidad int not null,
iva int not null,
primary key(ID_INSUMO));

CREATE TABLE TipoInsumo(
ID_TIPOINSUMO int,
nombre varchar(11) not null,
FK_ID_INSUMO int not null,
primary key(ID_TIPOINSUMO));

CREATE TABLE Bodega(
ID_BODEGA int,
descripcion varchar(30) not null,
estado boolean not null,
primary key(ID_BODEGA));

CREATE TABLE Pedido(
ID_PEDIDO int,
FK_ID_CALENDARIO int,
plazo int not null,
fecha date not null,
exigencia varchar(100) not null,
estado boolean not null,
primary key(ID_PEDIDO, FK_ID_CALENDARIO));

CREATE TABLE Devolucion(
ID_DEVOLUCION int,
descripcion varchar(30) not null,
fecha date not null,
estado boolean not null,
FK_ID_PEDIDO int not null,
primary key(ID_DEVOLUCION));

CREATE TABLE Factura(
ID_FACTURA int,
fecha date not null,
FK_ID_PEDIDO int not null,
primary key(ID_FACTURA));

CREATE TABLE Usuario(
ID_USUARIO int,
prNombre varchar(10) not null,
prApellido varchar(10) not null,
contrasena varchar(25) not null,
rol varchar(20) not null,
primary key(ID_USUARIO));

CREATE TABLE Log(
ID_LOG int,
fecha date not null,
hora varchar(5),
descripcion varchar(50) not null,
FK_ID_USUARIO int not null,
primary key(ID_LOG));

CREATE TABLE VENTA_PRODUCCION(
FK_ID_PRODUCCION int,
FK_ID_VENTA int,
cantidad int not null,
primary key(FK_ID_PRODUCCION, FK_ID_VENTA));

CREATE TABLE CATPRODUCTO_MATERIAPRIMA(
FK_ID_CATPRODUCTO int,
FK_ID_MATERIAPRIMA int,
primary key(FK_ID_CATPRODUCTO, FK_ID_MATERIAPRIMA));

CREATE TABLE BODEGA_MATERIAPRIMA(
FK_ID_BODEGA int,
FK_ID_MATERIAPRIMA int,
FK_ID_CALENDARIO int,
fechaVencimiento date not null,
fechaRegistro date not null,
unidades int not null,
transaccion boolean not null,
primary key(FK_ID_BODEGA, FK_ID_MATERIAPRIMA, FK_ID_CALENDARIO));

CREATE TABLE BODEGA_INSUMO(
FK_ID_BODEGA int,
FK_ID_INSUMO int,
fechaRegistro date not null,
transaccion boolean not null,
unidades int not null,
primary key(FK_ID_BODEGA, FK_ID_INSUMO));

CREATE TABLE PROVEEDOR_INSUMO(
FK_ID_PROVEEDOR int,
FK_ID_INSUMO int,
estado boolean not null,
primary key(FK_ID_PROVEEDOR, FK_ID_INSUMO));

CREATE TABLE PROVEEDOR_MATERIAPRIMA(
FK_ID_MATERIAPRIMA int,
FK_ID_PROVEEDOR int,
estado boolean not null,
primary key(FK_ID_MATERIAPRIMA, FK_ID_PROVEEDOR));

CREATE TABLE PEDIDO_MATERIAPRIMA(
FK_ID_PEDIDO int,
FK_ID_MATERIAPRIMA int,
unidades int not null,
cancelado boolean not null,
primary key(FK_ID_PEDIDO, FK_ID_MATERIAPRIMA));

CREATE TABLE PEDIDO_INSUMO(
FK_ID_PEDIDO int,
FK_ID_INSUMO int,
unidades int not null,
cancelado boolean not null,
primary key(FK_ID_PEDIDO, FK_ID_INSUMO));

CREATE TABLE PEDIDO_PROVEEDOR(
FK_ID_PEDIDO int,
FK_ID_PROVEEDOR int,
primary key(FK_ID_PEDIDO, FK_ID_PROVEEDOR));

CREATE TABLE Telefono(
FK_ID_PROVEEDOR int,
ID_TELEFONO varchar(12),
primary key(FK_ID_PROVEEDOR, ID_TELEFONO));

-- LLaves Foraneas

ALTER TABLE SubtipoProducto ADD CONSTRAINT FK_ID_TIPOPRODUCTO_SUBTIPOPRODUCTO FOREIGN KEY(FK_ID_TIPOPRODUCTO) REFERENCES TipoProducto(ID_TIPOPRODUCTO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE CatProducto ADD CONSTRAINT FK_ID_SUBTIPOPRODUCTO_CATPRODUCTO FOREIGN KEY(FK_ID_SUBTIPOPRODUCTO) REFERENCES SubtipoProducto(ID_SUBTIPOPRODUCTO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Produccion ADD CONSTRAINT FK_ID_CALENDARIO_PRODUCCION FOREIGN KEY(FK_ID_CALENDARIO) REFERENCES Calendario(ID_CALENDARIO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Produccion ADD CONSTRAINT FK_ID_CATPRODUCTO_PRODUCCION FOREIGN KEY(FK_ID_CATPRODUCTO) REFERENCES CatProducto(ID_CATPRODUCTO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE VENTA_PRODUCCION ADD CONSTRAINT FK_ID_PRODUCCION_VENTA_PRODUCCION FOREIGN KEY(FK_ID_PRODUCCION) REFERENCES Produccion(ID_PRODUCCION) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE VENTA_PRODUCCION ADD CONSTRAINT FK_ID_VENTA_VENTA FOREIGN KEY(FK_ID_VENTA) REFERENCES Venta(ID_VENTA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE EventoEspecifico ADD CONSTRAINT FK_ID_CALENDARIO_EVENTOESPECIFICO FOREIGN KEY(FK_ID_CALENDARIO) REFERENCES Calendario(ID_CALENDARIO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE BODEGA_MATERIAPRIMA ADD CONSTRAINT FK_ID_BODEGA_BODEGA_MATERIAPRIMA FOREIGN KEY(FK_ID_BODEGA) REFERENCES Bodega(ID_BODEGA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE BODEGA_MATERIAPRIMA ADD CONSTRAINT FK_ID_MATERIAPRIMA_BODEGA_MATERIAPRIMA FOREIGN KEY(FK_ID_MATERIAPRIMA) REFERENCES MateriaPrima(ID_MATERIAPRIMA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE BODEGA_MATERIAPRIMA ADD CONSTRAINT FK_ID_CALENDARIO_BODEGA_MATERIAPRIMA FOREIGN KEY(FK_ID_CALENDARIO) REFERENCES Calendario(ID_CALENDARIO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE MedidaCantidad ADD CONSTRAINT FK_ID_MATERIAPRIMA_MEDIDACANTIDAD FOREIGN KEY(FK_ID_MATERIAPRIMA) REFERENCES MateriaPrima(ID_MATERIAPRIMA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE BODEGA_INSUMO ADD CONSTRAINT FK_ID_BODEGA_BODEGA_INSUMO FOREIGN KEY(FK_ID_BODEGA) REFERENCES Bodega(ID_BODEGA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE BODEGA_INSUMO ADD CONSTRAINT FK_ID_INSUMO_BODEGA_INSUMO FOREIGN KEY(FK_ID_INSUMO) REFERENCES Insumo(ID_INSUMO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PROVEEDOR_MATERIAPRIMA ADD CONSTRAINT FK_ID_MATERIAPRIMA_PROVEEDOR_MATERIAPRIMA FOREIGN KEY(FK_ID_MATERIAPRIMA) REFERENCES MateriaPrima(ID_MATERIAPRIMA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PROVEEDOR_MATERIAPRIMA ADD CONSTRAINT FK_ID_PROVEEDOR_PROVEEDOR_MATERIAPRIMA FOREIGN KEY(FK_ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PEDIDO_MATERIAPRIMA ADD CONSTRAINT FK_ID_PEDIDO_PEDIDO_MATERIAPRIMA FOREIGN KEY(FK_ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PEDIDO_MATERIAPRIMA ADD CONSTRAINT FK_ID_MATERIAPRIMA_PEDIDO_MATERIAPRIMA FOREIGN KEY(FK_ID_MATERIAPRIMA) REFERENCES MateriaPrima(ID_MATERIAPRIMA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PEDIDO_PROVEEDOR ADD CONSTRAINT FK_ID_PEDIDO_PEDIDO_PROVEEDOR FOREIGN KEY(FK_ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PEDIDO_PROVEEDOR ADD CONSTRAINT FK_ID_PROVEEDOR_PEDIDO_PROVEEDOR FOREIGN KEY(FK_ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PROVEEDOR_INSUMO ADD CONSTRAINT FK_ID_PROVEEDOR_PROVEEDOR_INSUMO FOREIGN KEY(FK_ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PROVEEDOR_INSUMO ADD CONSTRAINT FK_ID_INSUMO_PROVEEDOR_INSUMO FOREIGN KEY(FK_ID_INSUMO) REFERENCES Insumo(ID_INSUMO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE TipoMateriaPrima ADD CONSTRAINT FK_ID_MATERIAPRIMA_TIPOMATERIAPRIMA FOREIGN KEY(FK_ID_MATERIAPRIMA) REFERENCES MateriaPrima(ID_MATERIAPRIMA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Devolucion ADD CONSTRAINT FK_ID_PEDIDO_DEVOLUCION FOREIGN KEY(FK_ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Pedido ADD CONSTRAINT FK_ID_CALENDARIO_PEDIDO FOREIGN KEY(FK_ID_CALENDARIO) REFERENCES Calendario(ID_CALENDARIO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Factura ADD CONSTRAINT FK_ID_PEDIDO_FACTURA FOREIGN KEY(FK_ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Telefono ADD CONSTRAINT FK_ID_PROVEEDOR_TELEFONO FOREIGN KEY(FK_ID_PROVEEDOR) REFERENCES Proveedor(ID_PROVEEDOR) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PEDIDO_INSUMO ADD CONSTRAINT FK_ID_PEDIDO_PEDIDO_INSUMO FOREIGN KEY(FK_ID_PEDIDO) REFERENCES Pedido(ID_PEDIDO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PEDIDO_INSUMO ADD CONSTRAINT FK_ID_INSUMO_PEDIDO_INSUMO FOREIGN KEY(FK_ID_INSUMO) REFERENCES Insumo(ID_INSUMO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE TipoInsumo ADD CONSTRAINT FK_ID_INSUMO_TIPOINSUMO FOREIGN KEY(FK_ID_INSUMO) REFERENCES Insumo(ID_INSUMO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Log ADD CONSTRAINT FK_ID_USUARIO_LOG FOREIGN KEY(FK_ID_USUARIO) REFERENCES Usuario(ID_USUARIO) ON UPDATE CASCADE ON DELETE CASCADE;