CREATE DATABASE IF NOT EXISTS `panaderiaerp`;

USE `panaderiaerp`;

SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `agenda`;

CREATE TABLE `agenda` (
  `id` int(10) unsigned NOT NULL,
  `title` varchar(150) COLLATE utf8_spanish_ci DEFAULT NULL,
  `body` text COLLATE utf8_spanish_ci NOT NULL,
  `url` varchar(150) COLLATE utf8_spanish_ci NOT NULL,
  `class` varchar(45) COLLATE utf8_spanish_ci NOT NULL DEFAULT 'event-important',
  `start` varchar(15) COLLATE utf8_spanish_ci NOT NULL,
  `end` varchar(15) COLLATE utf8_spanish_ci NOT NULL,
  `inicio_normal` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `final_normal` varchar(50) COLLATE utf8_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

INSERT INTO `agenda` VALUES (89,"Prueba_1","Esta es la descripción","http://localhost/linea/backend/calendario/descripcion_evento.php?id=89","event-success",1583862720000,1583430720000,"10/03/2020 12:52:00","05/03/2020 12:52:00"),
(90,"sds","dsadsa","http://localhost/linea/backend/calendario/descripcion_evento.php?id=90","event-info",1584294780000,1584381180000,"15/03/2020 12:53:00","16/03/2020 12:53:00"),
(92,"Esto es un titulo especial","el evento es especial.","http://localhost/linea/backend/calendario/descripcion_evento.php?id=92","event-special",1584594000000,1584939600000,"19/03/2020 00:00:00","23/03/2020 00:00:00");


DROP TABLE IF EXISTS `bodega`;

CREATE TABLE `bodega` (
  `ID_BODEGA` int(11) NOT NULL,
  `descripcion` varchar(30) NOT NULL,
  `estado` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_BODEGA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `bodega_insumo`;

CREATE TABLE `bodega_insumo` (
  `FK_ID_BODEGA` int(11) NOT NULL,
  `FK_ID_INSUMO` int(11) NOT NULL,
  `fechaRegistro` date NOT NULL,
  `transaccion` tinyint(1) NOT NULL,
  `unidades` int(11) NOT NULL,
  PRIMARY KEY (`FK_ID_BODEGA`,`FK_ID_INSUMO`),
  KEY `FK_ID_INSUMO_BODEGA_INSUMO` (`FK_ID_INSUMO`),
  CONSTRAINT `FK_ID_BODEGA_BODEGA_INSUMO` FOREIGN KEY (`FK_ID_BODEGA`) REFERENCES `bodega` (`ID_BODEGA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_INSUMO_BODEGA_INSUMO` FOREIGN KEY (`FK_ID_INSUMO`) REFERENCES `insumo` (`ID_INSUMO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `bodega_materiaprima`;

CREATE TABLE `bodega_materiaprima` (
  `FK_ID_BODEGA` int(11) NOT NULL,
  `FK_ID_MATERIAPRIMA` int(11) NOT NULL,
  `FK_ID_CALENDARIO` int(11) NOT NULL,
  `fechaVencimiento` date NOT NULL,
  `fechaRegistro` date NOT NULL,
  `unidades` int(11) NOT NULL,
  `transaccion` tinyint(1) NOT NULL,
  PRIMARY KEY (`FK_ID_BODEGA`,`FK_ID_MATERIAPRIMA`,`FK_ID_CALENDARIO`),
  KEY `FK_ID_MATERIAPRIMA_BODEGA_MATERIAPRIMA` (`FK_ID_MATERIAPRIMA`),
  KEY `FK_ID_CALENDARIO_BODEGA_MATERIAPRIMA` (`FK_ID_CALENDARIO`),
  CONSTRAINT `FK_ID_BODEGA_BODEGA_MATERIAPRIMA` FOREIGN KEY (`FK_ID_BODEGA`) REFERENCES `bodega` (`ID_BODEGA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_CALENDARIO_BODEGA_MATERIAPRIMA` FOREIGN KEY (`FK_ID_CALENDARIO`) REFERENCES `calendario` (`ID_CALENDARIO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_MATERIAPRIMA_BODEGA_MATERIAPRIMA` FOREIGN KEY (`FK_ID_MATERIAPRIMA`) REFERENCES `materiaprima` (`ID_MATERIAPRIMA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `calendario`;

CREATE TABLE `calendario` (
  `ID_CALENDARIO` int(11) NOT NULL,
  `nombre` varchar(30) NOT NULL,
  `hora` varchar(5) NOT NULL,
  `detalles` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_CALENDARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `catproducto`;

CREATE TABLE `catproducto` (
  `ID_CATPRODUCTO` int(11) NOT NULL,
  `nombre` varchar(10) NOT NULL,
  `descripcion` varchar(40) NOT NULL,
  `precio` int(11) NOT NULL,
  `stock` int(11) NOT NULL,
  `imagen` varchar(200) NOT NULL,
  `duracion` int(11) NOT NULL,
  `sabor` varchar(12) NOT NULL,
  `iva` int(11) NOT NULL,
  `estado` tinyint(1) NOT NULL,
  `FK_ID_SUBTIPOPRODUCTO` int(11) NOT NULL,
  PRIMARY KEY (`ID_CATPRODUCTO`),
  KEY `FK_ID_SUBTIPOPRODUCTO_CATPRODUCTO` (`FK_ID_SUBTIPOPRODUCTO`),
  CONSTRAINT `FK_ID_SUBTIPOPRODUCTO_CATPRODUCTO` FOREIGN KEY (`FK_ID_SUBTIPOPRODUCTO`) REFERENCES `subtipoproducto` (`ID_SUBTIPOPRODUCTO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `catproducto_materiaprima`;

CREATE TABLE `catproducto_materiaprima` (
  `FK_ID_CATPRODUCTO` int(11) NOT NULL,
  `FK_ID_MATERIAPRIMA` int(11) NOT NULL,
  PRIMARY KEY (`FK_ID_CATPRODUCTO`,`FK_ID_MATERIAPRIMA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `devolucion`;

CREATE TABLE `devolucion` (
  `ID_DEVOLUCION` int(11) NOT NULL,
  `descripcion` varchar(30) NOT NULL,
  `fecha` date NOT NULL,
  `estado` tinyint(1) NOT NULL,
  `FK_ID_PEDIDO` int(11) NOT NULL,
  PRIMARY KEY (`ID_DEVOLUCION`),
  KEY `FK_ID_PEDIDO_DEVOLUCION` (`FK_ID_PEDIDO`),
  CONSTRAINT `FK_ID_PEDIDO_DEVOLUCION` FOREIGN KEY (`FK_ID_PEDIDO`) REFERENCES `pedido` (`ID_PEDIDO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `eventoespecifico`;

CREATE TABLE `eventoespecifico` (
  `ID_EVENTOESPECIFICO` int(11) NOT NULL,
  `FK_ID_CALENDARIO` int(11) NOT NULL,
  `fecha` date NOT NULL,
  PRIMARY KEY (`ID_EVENTOESPECIFICO`,`FK_ID_CALENDARIO`),
  KEY `FK_ID_CALENDARIO_EVENTOESPECIFICO` (`FK_ID_CALENDARIO`),
  CONSTRAINT `FK_ID_CALENDARIO_EVENTOESPECIFICO` FOREIGN KEY (`FK_ID_CALENDARIO`) REFERENCES `calendario` (`ID_CALENDARIO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `factura`;

CREATE TABLE `factura` (
  `ID_FACTURA` int(11) NOT NULL,
  `fecha` date NOT NULL,
  `FK_ID_PEDIDO` int(11) NOT NULL,
  PRIMARY KEY (`ID_FACTURA`),
  KEY `FK_ID_PEDIDO_FACTURA` (`FK_ID_PEDIDO`),
  CONSTRAINT `FK_ID_PEDIDO_FACTURA` FOREIGN KEY (`FK_ID_PEDIDO`) REFERENCES `pedido` (`ID_PEDIDO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `insumo`;

CREATE TABLE `insumo` (
  `ID_INSUMO` int(11) NOT NULL,
  `nombre` varchar(10) NOT NULL,
  `stock` int(11) NOT NULL,
  `descripcion` varchar(30) NOT NULL,
  `precio` int(11) NOT NULL,
  `cantidad` int(11) NOT NULL,
  `iva` int(11) NOT NULL,
  `estado` tinyint(1) NOT NULL,
  `FK_ID_TIPOINSUMO` int(11) NOT NULL,
  PRIMARY KEY (`ID_INSUMO`),
  KEY `FK_ID_TIPOINSUMO_INSUMO` (`FK_ID_TIPOINSUMO`),
  CONSTRAINT `FK_ID_TIPOINSUMO_INSUMO` FOREIGN KEY (`FK_ID_TIPOINSUMO`) REFERENCES `tipoinsumo` (`ID_TIPOINSUMO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `log`;

CREATE TABLE `log` (
  `ID_LOG` int(11) NOT NULL,
  `fecha` date NOT NULL,
  `hora` varchar(5) DEFAULT NULL,
  `descripcion` varchar(50) NOT NULL,
  `FK_ID_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ID_LOG`),
  KEY `FK_ID_USUARIO_LOG` (`FK_ID_USUARIO`),
  CONSTRAINT `FK_ID_USUARIO_LOG` FOREIGN KEY (`FK_ID_USUARIO`) REFERENCES `usuario` (`ID_USUARIO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `materiaprima`;

CREATE TABLE `materiaprima` (
  `ID_MATERIAPRIMA` int(11) NOT NULL,
  `nombre` varchar(10) NOT NULL,
  `cantidad` int(11) NOT NULL,
  `descripcion` varchar(30) NOT NULL,
  `precio` int(11) NOT NULL,
  `iva` int(11) NOT NULL,
  `stock` int(11) NOT NULL,
  `estado` tinyint(1) NOT NULL,
  `FK_ID_MEDIDACANTIDAD` int(11) NOT NULL,
  `FK_ID_TIPOMATERIAPRIMA` int(11) NOT NULL,
  PRIMARY KEY (`ID_MATERIAPRIMA`),
  KEY `FK_ID_TIPOMATERIAPRIMA_MateriaPrima` (`FK_ID_TIPOMATERIAPRIMA`),
  CONSTRAINT `FK_ID_MEDIDACANTIDAD_MATERIAPRIMA` FOREIGN KEY (`FK_ID_TIPOMATERIAPRIMA`) REFERENCES `tipomateriaprima` (`ID_TIPOMATERIAPRIMA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_TIPOMATERIAPRIMA_MateriaPrima` FOREIGN KEY (`FK_ID_TIPOMATERIAPRIMA`) REFERENCES `tipomateriaprima` (`ID_TIPOMATERIAPRIMA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `medidacantidad`;

CREATE TABLE `medidacantidad` (
  `ID_MEDIDACANTIDAD` int(11) NOT NULL,
  `nombre` varchar(3) NOT NULL,
  PRIMARY KEY (`ID_MEDIDACANTIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `pedido`;

CREATE TABLE `pedido` (
  `ID_PEDIDO` int(11) NOT NULL,
  `FK_ID_CALENDARIO` int(11) NOT NULL,
  `plazo` int(11) NOT NULL,
  `fecha` date NOT NULL,
  `exigencia` varchar(100) NOT NULL,
  `estado` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`,`FK_ID_CALENDARIO`),
  KEY `FK_ID_CALENDARIO_PEDIDO` (`FK_ID_CALENDARIO`),
  CONSTRAINT `FK_ID_CALENDARIO_PEDIDO` FOREIGN KEY (`FK_ID_CALENDARIO`) REFERENCES `calendario` (`ID_CALENDARIO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `pedido_insumo`;

CREATE TABLE `pedido_insumo` (
  `FK_ID_PEDIDO` int(11) NOT NULL,
  `FK_ID_INSUMO` int(11) NOT NULL,
  `unidades` int(11) NOT NULL,
  `cancelado` tinyint(1) NOT NULL,
  PRIMARY KEY (`FK_ID_PEDIDO`,`FK_ID_INSUMO`),
  KEY `FK_ID_INSUMO_PEDIDO_INSUMO` (`FK_ID_INSUMO`),
  CONSTRAINT `FK_ID_INSUMO_PEDIDO_INSUMO` FOREIGN KEY (`FK_ID_INSUMO`) REFERENCES `insumo` (`ID_INSUMO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_PEDIDO_PEDIDO_INSUMO` FOREIGN KEY (`FK_ID_PEDIDO`) REFERENCES `pedido` (`ID_PEDIDO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `pedido_materiaprima`;

CREATE TABLE `pedido_materiaprima` (
  `FK_ID_PEDIDO` int(11) NOT NULL,
  `FK_ID_MATERIAPRIMA` int(11) NOT NULL,
  `unidades` int(11) NOT NULL,
  `cancelado` tinyint(1) NOT NULL,
  PRIMARY KEY (`FK_ID_PEDIDO`,`FK_ID_MATERIAPRIMA`),
  KEY `FK_ID_MATERIAPRIMA_PEDIDO_MATERIAPRIMA` (`FK_ID_MATERIAPRIMA`),
  CONSTRAINT `FK_ID_MATERIAPRIMA_PEDIDO_MATERIAPRIMA` FOREIGN KEY (`FK_ID_MATERIAPRIMA`) REFERENCES `materiaprima` (`ID_MATERIAPRIMA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_PEDIDO_PEDIDO_MATERIAPRIMA` FOREIGN KEY (`FK_ID_PEDIDO`) REFERENCES `pedido` (`ID_PEDIDO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `pedido_proveedor`;

CREATE TABLE `pedido_proveedor` (
  `FK_ID_PEDIDO` int(11) NOT NULL,
  `FK_ID_PROVEEDOR` int(11) NOT NULL,
  PRIMARY KEY (`FK_ID_PEDIDO`,`FK_ID_PROVEEDOR`),
  KEY `FK_ID_PROVEEDOR_PEDIDO_PROVEEDOR` (`FK_ID_PROVEEDOR`),
  CONSTRAINT `FK_ID_PEDIDO_PEDIDO_PROVEEDOR` FOREIGN KEY (`FK_ID_PEDIDO`) REFERENCES `pedido` (`ID_PEDIDO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_PROVEEDOR_PEDIDO_PROVEEDOR` FOREIGN KEY (`FK_ID_PROVEEDOR`) REFERENCES `proveedor` (`ID_PROVEEDOR`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `produccion`;

CREATE TABLE `produccion` (
  `ID_PRODUCCION` int(11) NOT NULL,
  `FK_ID_CALENDARIO` int(11) NOT NULL,
  `fechaProduccion` date NOT NULL,
  `unidades` int(11) NOT NULL,
  `cantidadInicial` int(11) NOT NULL,
  `FK_ID_CATPRODUCTO` int(11) NOT NULL,
  PRIMARY KEY (`ID_PRODUCCION`,`FK_ID_CALENDARIO`),
  KEY `FK_ID_CALENDARIO_PRODUCCION` (`FK_ID_CALENDARIO`),
  KEY `FK_ID_CATPRODUCTO_PRODUCCION` (`FK_ID_CATPRODUCTO`),
  CONSTRAINT `FK_ID_CALENDARIO_PRODUCCION` FOREIGN KEY (`FK_ID_CALENDARIO`) REFERENCES `calendario` (`ID_CALENDARIO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_CATPRODUCTO_PRODUCCION` FOREIGN KEY (`FK_ID_CATPRODUCTO`) REFERENCES `catproducto` (`ID_CATPRODUCTO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `proveedor`;

CREATE TABLE `proveedor` (
  `ID_PROVEEDOR` int(11) NOT NULL,
  `prNombre` varchar(10) NOT NULL,
  `segNombre` varchar(10) NOT NULL,
  `prApellido` varchar(10) NOT NULL,
  `segApellido` varchar(10) NOT NULL,
  `correo` varchar(30) NOT NULL,
  `estado` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_PROVEEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `proveedor_insumo`;

CREATE TABLE `proveedor_insumo` (
  `FK_ID_PROVEEDOR` int(11) NOT NULL,
  `FK_ID_INSUMO` int(11) NOT NULL,
  `estado` tinyint(1) NOT NULL,
  PRIMARY KEY (`FK_ID_PROVEEDOR`,`FK_ID_INSUMO`),
  KEY `FK_ID_INSUMO_PROVEEDOR_INSUMO` (`FK_ID_INSUMO`),
  CONSTRAINT `FK_ID_INSUMO_PROVEEDOR_INSUMO` FOREIGN KEY (`FK_ID_INSUMO`) REFERENCES `insumo` (`ID_INSUMO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_PROVEEDOR_PROVEEDOR_INSUMO` FOREIGN KEY (`FK_ID_PROVEEDOR`) REFERENCES `proveedor` (`ID_PROVEEDOR`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `proveedor_materiaprima`;

CREATE TABLE `proveedor_materiaprima` (
  `FK_ID_MATERIAPRIMA` int(11) NOT NULL,
  `FK_ID_PROVEEDOR` int(11) NOT NULL,
  `estado` tinyint(1) NOT NULL,
  PRIMARY KEY (`FK_ID_MATERIAPRIMA`,`FK_ID_PROVEEDOR`),
  KEY `FK_ID_PROVEEDOR_PROVEEDOR_MATERIAPRIMA` (`FK_ID_PROVEEDOR`),
  CONSTRAINT `FK_ID_MATERIAPRIMA_PROVEEDOR_MATERIAPRIMA` FOREIGN KEY (`FK_ID_MATERIAPRIMA`) REFERENCES `materiaprima` (`ID_MATERIAPRIMA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_PROVEEDOR_PROVEEDOR_MATERIAPRIMA` FOREIGN KEY (`FK_ID_PROVEEDOR`) REFERENCES `proveedor` (`ID_PROVEEDOR`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `subtipoproducto`;

CREATE TABLE `subtipoproducto` (
  `ID_SUBTIPOPRODUCTO` int(11) NOT NULL,
  `nombre` varchar(10) NOT NULL,
  `FK_ID_TIPOPRODUCTO` int(11) NOT NULL,
  PRIMARY KEY (`ID_SUBTIPOPRODUCTO`),
  KEY `FK_ID_TIPOPRODUCTO_SUBTIPOPRODUCTO` (`FK_ID_TIPOPRODUCTO`),
  CONSTRAINT `FK_ID_TIPOPRODUCTO_SUBTIPOPRODUCTO` FOREIGN KEY (`FK_ID_TIPOPRODUCTO`) REFERENCES `tipoproducto` (`ID_TIPOPRODUCTO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `telefono`;

CREATE TABLE `telefono` (
  `FK_ID_PROVEEDOR` int(11) NOT NULL,
  `ID_TELEFONO` varchar(12) NOT NULL,
  PRIMARY KEY (`FK_ID_PROVEEDOR`,`ID_TELEFONO`),
  CONSTRAINT `FK_ID_PROVEEDOR_TELEFONO` FOREIGN KEY (`FK_ID_PROVEEDOR`) REFERENCES `proveedor` (`ID_PROVEEDOR`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `tipoinsumo`;

CREATE TABLE `tipoinsumo` (
  `ID_TIPOINSUMO` int(11) NOT NULL,
  `nombre` varchar(11) NOT NULL,
  PRIMARY KEY (`ID_TIPOINSUMO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `tipomateriaprima`;

CREATE TABLE `tipomateriaprima` (
  `ID_TIPOMATERIAPRIMA` int(11) NOT NULL,
  `nombre` varchar(15) NOT NULL,
  PRIMARY KEY (`ID_TIPOMATERIAPRIMA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `tipoproducto`;

CREATE TABLE `tipoproducto` (
  `ID_TIPOPRODUCTO` int(11) NOT NULL,
  `nombre` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`ID_TIPOPRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `usuario`;

CREATE TABLE `usuario` (
  `ID_USUARIO` int(11) NOT NULL,
  `prNombre` varchar(10) NOT NULL,
  `prApellido` varchar(10) NOT NULL,
  `contrasena` varchar(25) NOT NULL,
  `rol` varchar(20) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `usuario` VALUES (1,"osman","jimenez",1,1),
(2,"Pepe","Perez",2,2);


DROP TABLE IF EXISTS `venta`;

CREATE TABLE `venta` (
  `ID_VENTA` int(11) NOT NULL,
  `fecha` date NOT NULL,
  PRIMARY KEY (`ID_VENTA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



DROP TABLE IF EXISTS `venta_produccion`;

CREATE TABLE `venta_produccion` (
  `FK_ID_PRODUCCION` int(11) NOT NULL,
  `FK_ID_VENTA` int(11) NOT NULL,
  `cantidad` int(11) NOT NULL,
  PRIMARY KEY (`FK_ID_PRODUCCION`,`FK_ID_VENTA`),
  KEY `FK_ID_VENTA_VENTA` (`FK_ID_VENTA`),
  CONSTRAINT `FK_ID_PRODUCCION_VENTA_PRODUCCION` FOREIGN KEY (`FK_ID_PRODUCCION`) REFERENCES `produccion` (`ID_PRODUCCION`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ID_VENTA_VENTA` FOREIGN KEY (`FK_ID_VENTA`) REFERENCES `venta` (`ID_VENTA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



SET foreign_key_checks = 1;
